// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"
// import NestedFormController from '@stimulus-components/rails-nested-form';
// application.register('nested-form', NestedFormController);

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import TakeTimeController from "./take_time_controller"

application.register("take-time", TakeTimeController)
