// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DrugModalController from "./drug_modal_controller"
application.register("drug-modal", DrugModalController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MedicineModalController from "./medicine_modal_controller"
application.register("medicine-modal", MedicineModalController)
